trigger:
- main

variables:
  nodeVersion: '18.x'
  azureStorageAccount: 'shopctrldocs'
  containerName: '$web' # Static websites use $web container

stages:
- stage: Build
  displayName: Build Docusaurus
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    # Install NodeJS 
    - task: NodeTool@0
      inputs:
        versionSpec: $(nodeVersion)
      displayName: 'Install Node.js'
    # Install dependencies, build Docusaurus
    - script: |
        npm install
        npm run build
      displayName: 'Install dependencies and build'
      workingDirectory: $(System.DefaultWorkingDirectory)
    # Publish the artifact
    - publish: $(System.DefaultWorkingDirectory)/build
      artifact: docusaurus-build

- stage: Deploy
  displayName: 'Deploy to Azure Storage'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - job: Deploy
    displayName: 'Deploy'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: none
    - download: current
      artifact: docusaurus-build
    - task: AzureCLI@2
      displayName: 'Upload to Azure Storage'
      inputs:
        azureSubscription: '92577f71-89c4-4dd8-8685-2e5d159e18c5'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          
          az storage blob upload-batch \
            --account-name "$(azureStorageAccount)" \
            --destination "$(containerName)" \
            --source "$(Pipeline.Workspace)/docusaurus-build" \
            --overwrite \
            --content-type "text/html" \
            --pattern "*.html"

          az storage blob upload-batch \
            --account-name "$(azureStorageAccount)" \
            --destination "$(containerName)" \
            --source "$(Pipeline.Workspace)/docusaurus-build" \
            --overwrite \
            --content-type "text/css" \
            --pattern "*.css"

          az storage blob upload-batch \
            --account-name "$(azureStorageAccount)" \
            --destination "$(containerName)" \
            --source "$(Pipeline.Workspace)/docusaurus-build" \
            --overwrite \
            --content-type "text/plain" \
            --pattern "*.txt"

          az storage blob upload-batch \
            --account-name "$(azureStorageAccount)" \
            --destination "$(containerName)" \
            --source "$(Pipeline.Workspace)/docusaurus-build" \
            --overwrite \
            --content-type "application/javascript" \
            --pattern "*.js"

          az storage blob upload-batch \
            --account-name "$(azureStorageAccount)" \
            --destination "$(containerName)" \
            --source "$(Pipeline.Workspace)/docusaurus-build" \
            --overwrite \
            --content-type "application/json" \
            --pattern "*.json"

          az storage blob upload-batch \
            --account-name "$(azureStorageAccount)" \
            --destination "$(containerName)" \
            --source "$(Pipeline.Workspace)/docusaurus-build" \
            --overwrite \
            --content-type "application/xml" \
            --pattern "*.xml"

          az storage blob upload-batch \
            --account-name "$(azureStorageAccount)" \
            --destination "$(containerName)" \
            --source "$(Pipeline.Workspace)/docusaurus-build" \
            --overwrite \
            --content-type "image/png" \
            --pattern "*.png"

          az storage blob upload-batch \
            --account-name "$(azureStorageAccount)" \
            --destination "$(containerName)" \
            --source "$(Pipeline.Workspace)/docusaurus-build" \
            --overwrite \
            --content-type "image/jpeg" \
            --pattern "*.jpg"

          az storage blob upload-batch \
            --account-name "$(azureStorageAccount)" \
            --destination "$(containerName)" \
            --source "$(Pipeline.Workspace)/docusaurus-build" \
            --overwrite \
            --content-type "image/jpeg" \
            --pattern "*.jpeg"

          az storage blob upload-batch \
            --account-name "$(azureStorageAccount)" \
            --destination "$(containerName)" \
            --source "$(Pipeline.Workspace)/docusaurus-build" \
            --overwrite \
            --content-type "image/x-icon" \
            --pattern "*.ico"

          az storage blob upload-batch \
            --account-name "$(azureStorageAccount)" \
            --destination "$(containerName)" \
            --source "$(Pipeline.Workspace)/docusaurus-build" \
            --overwrite \
            --content-type "image/svg+xml" \
            --pattern "*.svg"

          az storage blob upload-batch \
            --account-name "$(azureStorageAccount)" \
            --destination "$(containerName)" \
            --source "$(Pipeline.Workspace)/docusaurus-build" \
            --overwrite \
            --content-type "image/gif" \
            --pattern "*.gif"

          az storage blob upload-batch \
            --account-name "$(azureStorageAccount)" \
            --destination "$(containerName)" \
            --source "$(Pipeline.Workspace)/docusaurus-build" \
            --overwrite \
            --content-type "video/mp4" \
            --pattern "*.mp4"
