trigger:
- main

variables:
  nodeVersion: '18.x'
  azureStorageAccount: 'shopctrldocs'
  containerName: '\$web' # Static websites use $web container

stages:
- stage: Build
  displayName: Build Docusaurus
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    # Install NodeJS 
    - task: NodeTool@0
      inputs:
        versionSpec: $(nodeVersion)
      displayName: 'Install Node.js'
    - task: Cache@2
      displayName: 'Cache NPM dependencies'
      inputs:
        key: '"node_modules" | "$(Agent.OS)" | package-lock.json'
        path: '$(System.DefaultWorkingDirectory)/node_modules'
        cacheHitVar: 'NPM_CACHE_RESTORED'
        restoreKeys: |
          "node_modules" | "$(Agent.OS)"
          "node_modules"
    - task: Cache@2
      displayName: 'Cache Docusaurus output'
      inputs:
        key: '"docusaurus_output" | "$(Agent.OS)" | docusaurus.config.js | package-lock.json'
        path: '$(System.DefaultWorkingDirectory)/.docusaurus'
        cacheHitVar: 'DOCUSAURUS_CACHE_RESTORED'
        restoreKeys: |
          "docusaurus_output" | "$(Agent.OS)"
          "docusaurus_output"
    - script: |
        npm install
      displayName: 'Install NPM dependencies'
      condition: ne(variables.NPM_CACHE_RESTORED, true)
      workingDirectory: $(System.DefaultWorkingDirectory)
    - script: |
        npm run build
      displayName: 'Build Docusaurus'
      workingDirectory: $(System.DefaultWorkingDirectory)
    - publish: $(System.DefaultWorkingDirectory)/build
      artifact: docusaurus-build

- stage: Deploy
  displayName: 'Deploy to Azure Storage'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - job: Deploy
    displayName: 'Deploy'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: none
    - download: current
      artifact: docusaurus-build
    - task: AzureCLI@2
      displayName: 'Upload to Azure Storage'
      inputs:
        azureSubscription: '92577f71-89c4-4dd8-8685-2e5d159e18c5'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          end=$(date -u -d "1 hour" '+%Y-%m-%dT%H:%MZ')
          sas=$(az storage container generate-sas \
            --account-name $(azureStorageAccount) \
            --name $(containerName) \
            --permissions acdlrw \
            --expiry $end \
            --auth-mode key \
            --output tsv)
          
          # Set Environment variable
          # For some reason, --sas-token still generates a warning
          export AZURE_STORAGE_SAS_TOKEN="$sas"
          
          azcopy sync "$(Pipeline.Workspace)/docusaurus-build/" \
            "https://$(azureStorageAccount).blob.core.windows.net/$(containerName)?$sas" \
            --recursive \
            --compare-hash="MD5" \
            --put-md5 \
            --delete-destination="true"
          
          # Set Cache-Control
          MAX_JOBS=32
          update_blob() {
            blob_name=$1
            if [[ "$blob_name" == *.html ]]; then
              cache_control_value="public, max-age=300, stale-while-revalidate=60"
            else
              cache_control_value="public, max-age=31536000, immutable"
            fi
            az storage blob update \
              --account-name $(azureStorageAccount) \
              --container-name $(containerName) \
              --sas-token "$sas" \
              --name "$blob_name" \
              --content-cache-control "$cache_control_value" \
              --output none
            
            wait
            echo "[$(date +%T)] Updated: $blob_name"
          }
          export -f update_blob
          az storage blob list \
            --account-name $(azureStorageAccount) \
            --container-name $(containerName) \
            --sas-token "$sas" \
            --query "[?properties.contentSettings.cacheControl == null || properties.contentSettings.cacheControl == ''].name" \
            --output tsv \
          | while read -r blob_name; do
            # Run worker in background
            update_blob "$blob_name" &
            # Enforce max parallel jobs
            while (( $(jobs -r | wc -l) >= MAX_JOBS )); do
              sleep 0.01
            done
          done

          # Wait for all jobs to complete
          wait
          while (( $(jobs -r | wc -l) >= 1 )); do
            sleep 0.01
          done
          echo "[$(date +%T)] All cache headers have been set"
