trigger:
- main

variables:
  nodeVersion: '18.x'
  azureStorageAccount: 'shopctrldocs'
  containerName: '$web' # Static websites use $web container

stages:
- stage: Build
  displayName: Build Docusaurus
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    # Install NodeJS 
    - task: NodeTool@0
      inputs:
        versionSpec: $(nodeVersion)
      displayName: 'Install Node.js'
    # Install dependencies, build Docusaurus
    - script: |
        npm install
        npm run build
      displayName: 'Install dependencies and build'
      workingDirectory: $(System.DefaultWorkingDirectory)
    # Publish the artifact
    - publish: $(System.DefaultWorkingDirectory)/build
      artifact: docusaurus-build

- stage: Deploy
  displayName: 'Deploy to Azure Storage'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - job: Deploy
    displayName: 'Deploy'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: none
    - download: current
      artifact: docusaurus-build
    - task: AzureCLI@2
      displayName: 'Upload to Azure Storage'
      inputs:
        azureSubscription: '92577f71-89c4-4dd8-8685-2e5d159e18c5'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |

          declare -A content_types=(
              [".html"]="text/html"
              [".css"]="text/css"
              [".js"]="application/javascript"
              [".json"]="application/json"
              [".xml"]="application/xml"
              [".png"]="image/png"
              [".jpg"]="image/jpeg"
              [".jpeg"]="image/jpeg"
              [".ico"]="image/x-icon"
              [".svg"]="image/svg+xml"
              [".gif"]="image/gif"
              [".mp4"]="video/mp4"
              [".txt"]="text/plain"
          )

          for extension in "${!content_types[@]}"; do
              echo "Uploading files with extension $extension (Content-Type: ${content_types[$extension]})"
              
              az storage blob upload-batch \
                  --account-name "$(azureStorageAccount)" \
                  --destination "$(containerName)" \
                  --source "$(Pipeline.Workspace)/docusaurus-build" \
                  --overwrite \
                  --content-type "${content_types[$extension]}" \
                  --pattern "*$extension"
          done